### ISSUE TITLE
ifpd_mkdb: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by christianddietrich** [ggirelli/iFISH-probe-design#13]
**Describe the bug**
"SyntaxError: invalid syntax" error message (ifpd_mkdb --list-refGenomes)

**To Reproduce**
apt update && apt install python3 python3-pip
python3 -m venv ifish
pip3 install ifpd
ifpd_mkdb / ifpd_mkdb --list-refGenomes

**Expected behavior**
show the list of available genomes

**Screenshots**
https://www1.xup.in/exec/ximg.php?fid=54671897

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: 9.9

**Comment by ggirelli** [comment]
Hi, thanks for the bug report and sorry for the inconvenience. Could you please share the output of the following command?
```ifpd_mkdb v0.0.1```
Also, if you run `/usr/bin/python3` does the Python3 console open?

**Comment by christianddietrich** [comment]
> ifpd_mkdb --version

```
(ifish) ifish@localhost:~$ ifpd_mkdb --version
  File "/data/ifish/bin/ifpd_mkdb", line 37
    assert_msg = f"invalid URI: '{das_uri}'."
                                            ^
SyntaxError: invalid syntax
```

> Also, if you run /usr/bin/python3 does the Python3 console open?

```
(ifish) ifish@localhost:~$ /usr/bin/python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Thank you!

**Comment by christianddietrich** [comment]
My bad:

F-strings were a new feature introduced in Python 3.6

**Comment by ggirelli** [comment]
Yep, that's it. I will update the setup.py classifiers to clarify that. Sorry for the confusion! I'll close this now :)
