### ISSUE TITLE
ifpd_serve: high cpu usage when idle

### ISSUE THREAD

**Issue by christianddietrich** [ggirelli/iFISH-probe-design#17]
**Describe the bug**
The CPU usage of ifpd_serve is 100% on a CPU core even if idling.

**To Reproduce**
1. pip3 install ifpd
2. ifpd_serve

**Expected behavior**
Idling at about 0% cpu usage.

**Desktop (please complete the following information):**
 - OS: Debian 9.9 (Python 3.7.4) / Debian 10.0 (Python 3.7.3)

**Additional context**
Tried it on Debian 9 and Debian 10. OT: Thanks for your help in #15

**Comment by ggirelli** [comment]
That's known behavior. There's no plan to change it for the time being (it might require moving from `bottle`/`paste` to a different type of web server. Let us know if you have any suggestions on how to fix/improve this or to make a pull request related to this issue :)
